### ISSUE TITLE
Error in executing the deployed service.

### ISSUE THREAD

**Issue by shamitb** [watson-developer-cloud/natural-language-classifier-nodejs#14]
When I ask a question like: How cold is it today?
The page in the Output section shows : Error. Not found
Here: http://natural-language-classifier-nodejs-shamitbagchi-2119.eu-gb.mybluemix.net/

**Comment by germanattanasio** [comment]
did you train a classifier?

**Comment by shamitb** [comment]
How do I need to this?

**Comment by germanattanasio** [comment]
Take a look at https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/nl-classifier/get_start.shtml

**Comment by shamitb** [comment]
So I need this package curl for this?

**Comment by germanattanasio** [comment]
curl comes with your computer and allows you to do HTTP requests. You need to create a classifier with the training data that is available [here](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/blob/master/training/weather_data_train.csv) and update the `CLASSIFIER_ID` environment variable as described in the README.md file

**Comment by shamitb** [comment]
Ah! I didnt realize this BlueMix project was NodeJS - I thought it was a Python based NLP package ...
