### ISSUE TITLE
stuck at loads

### ISSUE THREAD

**Issue by MichaelGhattas** [watson-developer-cloud/natural-language-classifier-nodejs#18]
Hey, I deployed with bluemix and something is wrong because it gets stuck at loading, any clue how to fix that ?  Link below, and nice job converting this to node.js 

http://ghattas-movie-assistant.mybluemix.net/

**Comment by jzhang300** [comment]
@MichaelGhattas: I just tried this myself, and it seems to be working now, see if you can try this again.  If it still has issues, it may also be that you've hit memory capacity on your account, so deleting other apps and services may help.
