### ISSUE TITLE
could not find service natural-language-classifier-standard to bind to app

### ISSUE THREAD

**Issue by Bayeswang** [watson-developer-cloud/natural-language-classifier-nodejs#37]
Hi, when I tried to cf push, then it shown failed, could not find service natural-language-classifier-standard to bind to app. 

Is there anyone know this trouble? Thank you.

**Comment by germanattanasio** [comment]
You need to create the service and bind it to the app. Take a look at the [Getting Started]( https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/blob/master/README.md#getting-started) section.
