### ISSUE TITLE
Output shown FAILED

### ISSUE THREAD

**Issue by Bayeswang** [watson-developer-cloud/natural-language-classifier-nodejs#38]
Hi, I have bind the nodejs application in bluemix and binded the nlc services in the app. but after I run the app, and tried to evaluate the queries, output at the buttom of the page shown "Failed" in red. 

Is there anyone could help on this trouble error? Thank you. @germanattanasio

**Comment by germanattanasio** [comment]
did you train the service with the weather data as in the readme ?

**Comment by Bayeswang** [comment]
it shown me that could not open the file "/training/weather_data_training.csv". 

after I entered below command:

curl -i -u "<username>":"<password>" -F training_data=@/training/weather_data_train.csv -F training_metadata="{\"language\":\"en\",\"name\":\"TutorialClassifier\"}" "https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers";

**Comment by Bayeswang** [comment]
@germanattanasio thanks for your response. this problem is fixed by the readme guidance. Thanks.
