### ISSUE TITLE
Output is not visible without scrolling

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/natural-language-classifier-nodejs#7]
Asking a question, either manually typed or suggested from the page, and pressing "ask", results in no visual feedback that anything has happened unless the user thinks to scroll down. The header sections are all too large and the Output section should not be beneath the sample questions and description.

**Comment by germanattanasio** [comment]
Fixed in 1ad374ec5a8b5d4d95ca97ae0f9fbe9640549a24.
