### ISSUE TITLE
Please italicize 'temperature' and 'conditions'

### ISSUE THREAD

**Issue by chinghuachen** [watson-developer-cloud/natural-language-classifier-nodejs#9]
In the text "Watch the Natural Language Classifier categorize your weather-related question. In this demo, the classifier is trained to determine whether the question is related to temperature or weather conditions." Please italicize the words "temperature" and "conditions". This is to increase visibility to the user that there are these two classes in this demo example.

**Comment by SirSpidey** [comment]
Updated code, but needs to be pushed to update the demo
